# Generated by Django 3.2.6 on 2021-08-25 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('username', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('is_super', models.BooleanField(default=False)),
                ('of_age', models.BooleanField(blank=True, default=False, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader', to=settings.AUTH_USER_MODEL, verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
        migrations.CreateModel(
            name='Blogger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('username', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='имя')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Электороная почта')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Город')),
                ('is_super', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogger', to=settings.AUTH_USER_MODEL, verbose_name='blogger')),
            ],
        ),
    ]
