# Generated by Django 3.2.6 on 2021-09-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_infopages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='board.topic'),
        ),
    ]
