# Generated by Django 3.2.6 on 2021-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_historicalboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('user', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='имя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-pk']},
        ),
    ]
